backend:
  name: git-gateway
  branch: dev
media_folder: 'static/'
media_library:
  name: cloudinary
  config:
    cloud_name: wommy
    api_key: 162565326766577
local_backend: true
collections:
- label: 'Files'
  name: 'files'
  files:
  - label: 'Art'
    name: 'art'
    file: 'data/art.yml'
    fields:
    - label: 'Items'
      label_singular: 'Item'
      name: 'items'
      widget: list
      add_to_top: true
      fields:
      - { label: 'Title', name: 'title', widget: 'string', default: '', hint: 'artwork name' }
      - { label: 'Image', name: 'img', widget: 'image', default: '', hint: 'check the checkbox, then click insert' }
      - { label: 'Width', name: 'width', widget: 'number', default: 1, hint: '2 for landscape' }
      - { label: 'Published', name: 'published', widget: 'string', required: false, hint: 'Month, Year' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, hint: 'media, separated by commas' }
