backend:
  name: git-gateway
  branch: dev
media_folder: 'static/'
media_library:
  name: cloudinary
  config:
    cloud_name: wommy
    api_key: 162565326766577
local_backend: true
collections:
- label: 'Art1'
  name: 'art1'
  files:
  - label: 'Art2'
    name: 'art2'
    file: 'data/art.yml'
    fields:
    - label: "Artwork"
      name: "artwork"
      widget: list
      collapsed: false
      fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Width', name: 'width', widget: 'number' }
      - { label: 'Published', name: 'published', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
