backend:
  name: git-gateway
  branch: dev
media_folder: 'static/'
local_backend: true
collections:
- label: 'Art1'
  name: 'art1'
  files:
  - label: 'Art2'
    name: 'art2'
    file: 'data/art.yml'
    fields:
    - label: "Art3"
      name: "art3"
      widget: list
      collapsed: false
      fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      # - { label: 'Image', name: 'img', widget: 'string' }
      # - { label: 'Width', name: 'width', widget: 'number' }
      # - { label: 'Published', name: 'published', widget: 'string' }
      # - { label: 'Tags', name: 'tags', widget: 'list' }
