backend:
  name: git-gateway
  branch: dev
media_folder: 'static/'
collections:
- label: 'Art'
  name: 'art'
  files:
  - label: 'Art'
    name: 'art'
    file: 'data/art.yml'
    fields:
    - label: "Art"
      name: "art"
      widget: list
      collapsed: false
      fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'string' }
      - { label: 'Width', name: 'width', widget: 'number' }
      - { label: 'Published', name: 'published', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
