backend:
  name: git-gateway
  branch: dev
media_folder: 'static/'
collections:
  - name: 'art'
    label: 'Art'
    title: 'art'
    files:
      - name: 'art'
        label: 'Art'
        title: 'art'
        file: 'data/art.yml'
        fields:
            - { label: 'Name', name: 'name', widget: 'string' }
            - { label: 'Image', name: 'img', widget: 'string' }
            - { label: 'Width', name: 'width', widget: 'number' }
            - { label: 'Published', name: 'published', widget: 'string' }
            - { label: 'Tags', name: 'tags', widget: 'list' }
