backend:
  name: git-gateway
  branch: dev
media_folder: 'static/'
media_library:
  name: cloudinary
  config:
    cloud_name: wommy
    api_key: 162565326766577
local_backend: true
collections:
- label: 'Files'
  name: 'files'
  files:
  - label: 'Art'
    name: 'art'
    file: 'data/art.yml'
    fields:
    - label: 'Items'
      label_singular: 'item'
      name: 'items'
      widget: list
      add_to_top: true
      fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Width', name: 'width', widget: 'number' }
      - { label: 'Published', name: 'published', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  - label: 'Archive'
    name: 'archive'
    file: 'data/archive.yml'
    fields:
    - label: 'Monoprint'
      name: 'monoprint'
      widget: list
      add_to_top: true
      fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Width', name: 'width', widget: 'number' }
      - { label: 'Published', name: 'published', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
    - label: 'Undergrad'
      name: 'undergrad'
      widget: list
      add_to_top: true
      fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Width', name: 'width', widget: 'number' }
      - { label: 'Published', name: 'published', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
