backend:
  name: git-gateway
  branch: dev
media_folder: 'media/'
collections:
  - name: 'art'
    label: 'Art'
    title: 'art'
    folder: 'art'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
